let fieldsInit = {
    types: [
        {
            type: 'mushroomGood',
            src: './assets/images/mushroomGood.png',
            value: 2,
            alt: 'Dobry grzyb',
        },
        {
            type: 'mushroomWrong',
            src: './assets/images/mushroomWrong.png',
            value: -6,
            alt: 'Zły grzyb',
        },
        {
            type: 'raspberry',
            src: './assets/images/raspberry.png',
            value: 4,
            alt: 'Dobra borówka',
        },
        {
            type: 'special',
        },
        {
            type: 'natural',
        },
    ],
    properties: [
        { index: 0, xPrecent: 94.95, yPrecent: 94.99, type: 'natural' },
        { index: 1, xPrecent: 89.17, yPrecent: 95.12, type: 'natural' },
        { index: 2, xPrecent: 85.26, yPrecent: 95.19, type: 'natural' },
        {
            index: 3,
            xPrecent: 81.77,
            yPrecent: 95.12,
            type: 'raspberry',
            videoGroup: 'benefit',
            value: 1,
        },
        { index: 4, xPrecent: 78.33, yPrecent: 95.12, type: 'natural' },
        { index: 5, xPrecent: 73.91, yPrecent: 94.71, type: 'natural' },
        { index: 6, xPrecent: 70.05, yPrecent: 93.96, type: 'natural' },
        {
            index: 7,
            xPrecent: 66.35,
            yPrecent: 91.55,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 8, xPrecent: 63.49, yPrecent: 89.08, type: 'natural' },
        { index: 9, xPrecent: 60.62, yPrecent: 84.41, type: 'natural' },
        { index: 10, xPrecent: 58.54, yPrecent: 80.43, type: 'natural' },
        { index: 11, xPrecent: 57.08, yPrecent: 75.89, type: 'natural' },
        { index: 12, xPrecent: 56.67, yPrecent: 70.88, type: 'natural' },
        { index: 13, xPrecent: 57.4, yPrecent: 66.21, type: 'natural' },
        { index: 14, xPrecent: 60.26, yPrecent: 62.57, type: 'natural' },
        {
            index: 15,
            xPrecent: 63.13,
            yPrecent: 59.27,
            type: 'raspberry',
            videoGroup: 'benefit',
            value: 2,
        },
        { index: 16, xPrecent: 67.08, yPrecent: 58.93, type: 'natural' },
        {
            index: 17,
            xPrecent: 71.04,
            yPrecent: 59.96,
            type: 'mushroomGood',
            videoGroup: 'benefit',
            value: 2,
        },
        { index: 18, xPrecent: 75.16, yPrecent: 62.84, type: 'natural' },
        { index: 19, xPrecent: 77.4, yPrecent: 67.86, type: 'natural' },
        {
            index: 20,
            xPrecent: 77.97,
            yPrecent: 72.94,
            type: 'mushroomWrong',
            value: 1,
        },
        { index: 21, xPrecent: 79.64, yPrecent: 77.54, type: 'natural' },
        { index: 22, xPrecent: 82.19, yPrecent: 81.04, type: 'natural' },
        { index: 23, xPrecent: 85.83, yPrecent: 83.04, type: 'natural' },
        { index: 24, xPrecent: 89.69, yPrecent: 82.83, type: 'natural' },
        { index: 25, xPrecent: 92.97, yPrecent: 79.95, type: 'natural' },
        {
            index: 26,
            xPrecent: 95.26,
            yPrecent: 76.1,
            type: 'special',
            action: 'move',
            videoGroup: 'obstacle',
            value: -7,
            alertTitle: 'Wilk atakuje',
            alertButton: 'Uciekam!',
            alertContent:
                'Przestraszyło cię straszne zwierzę: cofasz się o 7-pól',
        },
        {
            index: 27,
            xPrecent: 96.72,
            yPrecent: 70.67,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 28, xPrecent: 96.72, yPrecent: 66.07, type: 'natural' },
        { index: 29, xPrecent: 95.99, yPrecent: 61.54, type: 'natural' },
        {
            index: 30,
            xPrecent: 93.33,
            yPrecent: 56.66,
            type: 'raspberry',
            value: 1,
        },
        { index: 31, xPrecent: 91.41, yPrecent: 52.75, type: 'natural' },
        { index: 32, xPrecent: 87.5, yPrecent: 46.63, type: 'natural' },
        { index: 33, xPrecent: 82.92, yPrecent: 42.51, type: 'natural' },
        {
            index: 34,
            xPrecent: 80.52,
            yPrecent: 39.35,
            type: 'special',
            videoGroup: 'help',
            action: 'extraTurn',
            alertTitle: 'Szlachetne serce!',
            alertButton: 'Ponowny Rzut',
            alertContent:
                'Uratowałeś pisklę, które wypadło z gniazda - możesz wykonać kolejny rzót kostką',
        },
        { index: 35, xPrecent: 78.28, yPrecent: 35.71, type: 'natural' },
        {
            index: 36,
            xPrecent: 76.04,
            yPrecent: 30.98,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 37, xPrecent: 73.96, yPrecent: 26.99, type: 'natural' },
        {
            index: 38,
            xPrecent: 72.4,
            yPrecent: 23.15,
            type: 'raspberry',
            value: 1,
        },
        {
            index: 39,
            xPrecent: 69.06,
            yPrecent: 19.02,
            type: 'special',
            videoGroup: 'wait',
            action: 'extraTurnForOther',
            alertTitle: 'Zabłądziłeś!',
            alertButton: 'Graj dalej',
            alertContent: 'Pomiliłeś ścieżki, czekasz kolejkę',
        },
        { index: 40, xPrecent: 65.1, yPrecent: 17.24, type: 'natural' },
        { index: 41, xPrecent: 61.04, yPrecent: 18.54, type: 'natural' },
        { index: 42, xPrecent: 58.13, yPrecent: 23.49, type: 'natural' },
        { index: 43, xPrecent: 56.61, yPrecent: 28.16, type: 'natural' },
        { index: 44, xPrecent: 57.6, yPrecent: 32.28, type: 'natural' },
        {
            index: 45,
            xPrecent: 60.52,
            yPrecent: 36.33,
            type: 'special',
            videoGroup: 'obstacle',
            value: 1,
            action: 'lostMushrooms',
            alertTitle: 'Gra warta świeczki',
            alertButton: 'Graj dalej',
            alertContent:
                'Wypadł ci koszyk, zbierasz grzyby tracąc losowego grzyba',
        },
        { index: 46, xPrecent: 61.46, yPrecent: 41.41, type: 'natural' },
        {
            index: 47,
            xPrecent: 60,
            yPrecent: 46.7,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 48, xPrecent: 57.97, yPrecent: 50.34, type: 'natural' },
        { index: 49, xPrecent: 53.85, yPrecent: 49.59, type: 'natural' },
        {
            index: 50,
            xPrecent: 49.38,
            yPrecent: 47.32,
            type: 'mushroomWrong',
            videoGroup: 'obstacle',
            value: 1,
        },
        {
            index: 51,
            xPrecent: 47.4,
            yPrecent: 42.99,
            type: 'raspberry',
            value: 1,
        },
        { index: 52, xPrecent: 45.83, yPrecent: 38.05, type: 'natural' },
        { index: 53, xPrecent: 44.58, yPrecent: 33.52, type: 'natural' },
        { index: 54, xPrecent: 44.06, yPrecent: 27.27, type: 'natural' },
        {
            index: 55,
            xPrecent: 43.13,
            yPrecent: 22.32,
            type: 'special',
            videoGroup: 'wait',
            action: 'extraTurnForOther',
            alertTitle: 'Dzięcioł',
            alertButton: 'Fajny Dzięcioł',
            alertContent: 'Zapatrzyłeś się na dzięcioła, czekasz kolejkę',
        },
        { index: 56, xPrecent: 41.67, yPrecent: 16.76, type: 'natural' },
        { index: 57, xPrecent: 38.7, yPrecent: 12.71, type: 'natural' },
        { index: 58, xPrecent: 34.17, yPrecent: 9.34, type: 'natural' },
        {
            index: 59,
            xPrecent: 29.84,
            yPrecent: 9.27,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 60, xPrecent: 26.61, yPrecent: 10.37, type: 'natural' },
        { index: 61, xPrecent: 21.82, yPrecent: 11.2, type: 'natural' },
        { index: 62, xPrecent: 18.18, yPrecent: 13.67, type: 'natural' },
        { index: 63, xPrecent: 12.55, yPrecent: 20.95, type: 'natural' },
        {
            index: 64,
            xPrecent: 9.01,
            yPrecent: 26.1,
            type: 'raspberry',
            value: 1,
        },
        { index: 65, xPrecent: 7.6, yPrecent: 31.87, type: 'natural' },
        {
            index: 66,
            xPrecent: 5.89,
            yPrecent: 37.43,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 67, xPrecent: 5.47, yPrecent: 44.02, type: 'natural' },
        { index: 68, xPrecent: 4.84, yPrecent: 50, type: 'natural' },
        {
            index: 69,
            xPrecent: 5.26,
            yPrecent: 55.98,
            type: 'special',
            videoGroup: 'obstacle',
            action: 'move',
            value: -12,
            alertTitle: 'Rwącą rzeczką...',
            alertButton: 'Wracam po koszyk',
            alertContent:
                'Koszyk wpadł do rzeczki, wracasz do pomostu by go odzyskać!',
        },
        { index: 70, xPrecent: 5.57, yPrecent: 62.16, type: 'natural' },
        {
            index: 71,
            xPrecent: 6.41,
            yPrecent: 67.79,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 72, xPrecent: 7.08, yPrecent: 73.7, type: 'natural' },
        { index: 73, xPrecent: 9.17, yPrecent: 78.3, type: 'natural' },
        { index: 74, xPrecent: 11.04, yPrecent: 82.35, type: 'natural' },
        {
            index: 75,
            xPrecent: 13.7,
            yPrecent: 86.26,
            type: 'mushroomGood',
            videoGroup: 'benefit',
            value: 3,
        },
        { index: 76, xPrecent: 16.88, yPrecent: 89.35, type: 'natural' },
        { index: 77, xPrecent: 20.83, yPrecent: 92.03, type: 'natural' },
        { index: 78, xPrecent: 24.79, yPrecent: 93.68, type: 'natural' },
        {
            index: 79,
            xPrecent: 29.53,
            yPrecent: 93.41,
            type: 'mushroomWrong',
            value: 1,
        },
        { index: 80, xPrecent: 32.92, yPrecent: 91.55, type: 'natural' },
        {
            index: 81,
            xPrecent: 35.92,
            yPrecent: 88.55,
            type: 'special',
            videoGroup: 'obstacle',
            value: 2,
            action: 'lostMushrooms',
            alertTitle: 'Toż to głaz',
            alertButton: 'Graj dalej',
            alertContent: 'Potykasz się o kamień i gubisz dwa grzybki',
        },
        { index: 82, xPrecent: 38.44, yPrecent: 83.31, type: 'natural' },
        { index: 83, xPrecent: 39.79, yPrecent: 78.64, type: 'natural' },
        {
            index: 84,
            xPrecent: 40.89,
            yPrecent: 73.08,
            type: 'mushroomGood',
            value: 2,
        },
        { index: 85, xPrecent: 41.35, yPrecent: 67.93, type: 'natural' },
        { index: 86, xPrecent: 41.2, yPrecent: 63.05, type: 'natural' },
        { index: 87, xPrecent: 40.21, yPrecent: 57.62, type: 'natural' },
        { index: 88, xPrecent: 38.85, yPrecent: 52.4, type: 'natural' },
        {
            index: 89,
            xPrecent: 36.46,
            yPrecent: 47.66,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 90, xPrecent: 32.55, yPrecent: 46.15, type: 'natural' },
        {
            index: 91,
            xPrecent: 28.33,
            yPrecent: 47.18,
            type: 'special',
            videoGroup: 'help',
            value: { number: 1, type: 'raspberry' },
            action: 'extraMushrooms',
            alertTitle: 'Pomocna dłoń!',
            alertButton: 'Graj dalej',
            alertContent:
                'Ratujesz zajączka, wyciągając go z sideł i otrzymujesz borówke!',
        },
        { index: 92, xPrecent: 26.56, yPrecent: 50.48, type: 'natural' },
        {
            index: 93,
            xPrecent: 27.14,
            yPrecent: 55.84,
            type: 'raspberry',
            value: 1,
        },
        { index: 94, xPrecent: 29.06, yPrecent: 60.85, type: 'natural' },
        { index: 95, xPrecent: 30.94, yPrecent: 66.48, type: 'natural' },
        { index: 96, xPrecent: 29.69, yPrecent: 71.29, type: 'natural' },
        { index: 97, xPrecent: 26.61, yPrecent: 74.52, type: 'natural' },
        {
            index: 98,
            xPrecent: 22.5,
            yPrecent: 74.86,
            type: 'mushroomGood',
            value: 1,
        },
        { index: 99, xPrecent: 19.27, yPrecent: 72.12, type: 'natural' },
        {
            index: 100,
            xPrecent: 16.93,
            yPrecent: 67.24,
            type: 'mushroomWrong',
            videoGroup: 'obstacle',
            value: 2,
        },
        { index: 101, xPrecent: 15.99, yPrecent: 62.09, type: 'natural' },
        { index: 102, xPrecent: 16.25, yPrecent: 56.25, type: 'natural' },
        { index: 103, xPrecent: 16.61, yPrecent: 50.14, type: 'natural' },
        { index: 104, xPrecent: 17.14, yPrecent: 43.68, type: 'natural' },
        {
            index: 105,
            xPrecent: 18.28,
            yPrecent: 37.23,
            type: 'special',
            videoGroup: 'obstacle',
            action: 'move',
            value: -11,
            alertTitle: 'Mrowisko!',
            alertButton: 'Odwrót!',
            alertContent: 'Uciekasz w popłochu do tyłu o 11 pól',
        },
        { index: 106, xPrecent: 18.91, yPrecent: 32.14, type: 'natural' },
        {
            index: 107,
            xPrecent: 18.39,
            yPrecent: 25.14,
            type: 'mushroomGood',
            videoGroup: 'benefit',
            value: 2,
        },
        { index: 108, xPrecent: 16.67, yPrecent: 19.37, type: 'natural' },
        { index: 109, xPrecent: 13.91, yPrecent: 14.7, type: 'natural' },
        {
            index: 110,
            xPrecent: 11.3,
            yPrecent: 10.1,
            type: 'special',
            videoGroup: 'gameEnd',
            action: 'playerFinised',
            value: [
                {
                    index: 0,
                    value: 5,
                },
                {
                    index: 1,
                    value: 3,
                },
                {
                    index: 2,
                    value: 1,
                },
            ],
            alertTitle: 'Konciec grzybobrania!',
            alertButton: 'Graj dalej',
            alertContent:
                'Otzymujesz dodatkowe punkty i czekasz na reszte graczy',
            lastField: true,
        },
    ],
};
export default fieldsInit;
